INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES ('CTLPTP', 'Laptop', 'Computers & Tablets', 1200, 27);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES ('CTTBLT', 'Tablet', 'Computers & Tablets', 700, 18);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES ('CPIPHN', 'iPhone', 'Cellphones', 1000, 80);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES ('CPGLXY', 'Galaxy', 'Cellphones', 900, 45);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES ('TV55IN', 'TV 55 Inches', 'TVs', 1200, 12);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES ('TV65IN', 'TV 65 Inches', 'TVs', 1500, 8);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES ('TV70IN', 'TV 70 Inches', 'TVs', 1800, 4);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES ('AUBSSP', 'Bose Speakers', 'Audio', 450, 50);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES ('AUBSHP', 'Bose Headphones', 'Audio', 300, 35);
INSERT INTO products (item_id, product_name, department_name, price, stock_quantity) VALUES ('AUBTHP', 'Beats Headphones', 'Audio', 300, 45);